version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    tty: true
  api:
    build: "./src"
    container_name: "api"
    working_dir: /home/node/app
    links:
      - mongodb
    environment:
      - NODE_ENV=development
    volumes:
      - ./src/api/:/home/node/app
    ports:
      - 8081:8081
    expose:
      - "8081"
    command: "yarn run dev"
    tty: true
  worker:
    build: "./src"
    container_name: "worker"
    working_dir: /home/node/app
    links:
      - mongodb
    environment:
      - NODE_ENV=development
    volumes:
      - ./src/worker/:/home/node/app
    command: "yarn run dev"
    tty: true